version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.free
    environment:
      - DB_PATH=/app/data/health.db
      - PORT=7860
    ports:
      - "7860:7860"
    volumes:
      - ../data:/app/data